import html
import os
import sys
import argparse
import pandas as pd
from datetime import datetime

# Add project root to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from services.recap_service import extract_weekly_data
import services.db_service as db_service
import services.ai_service as ai_service
from services.email_service import send_weekly_recap_email, _app_base_url, build_recap_email_html

def build_recap_html(week: int, summary_text: str) -> str:
    """HTML wrapper for the weekly recap email. The footer link points at the
    deployed app (APP_BASE_URL), not a hardcoded hostname."""
    base_url = _app_base_url()
    footer = (
        "This recap was generated by Gemini AI for the Wins Pool. "
        f'View the full standings at <a href="{base_url}">{base_url}</a>'
    )
    return build_recap_email_html(week, summary_text, footer_html=footer)

def main():
    parser = argparse.ArgumentParser(description="Generate AI Weekly Summary")
    parser.add_argument("--year", type=int, required=True, help="Season year")
    parser.add_argument("--week", type=int, required=True, help="NFL Week number")
    parser.add_argument("--dry-run", action="store_true", help="Print summary without saving/emailing")
    parser.add_argument("--show-prompt", action="store_true", help="Show the full prompt sent to AI for testing")
    args = parser.parse_args()

    print(f"--- Generating Recap for {args.year} Week {args.week} ---")
    
    data_summary, emails = extract_weekly_data(args.year, args.week)
    if not data_summary:
        return

    if args.show_prompt:
        full_prompt = ai_service.get_recap_prompt(data_summary)
        print("\n" + "!"*50)
        print("FULL AI PROMPT (FOR MANUAL TESTING):")
        print("!"*50)
        print(full_prompt)
        print("!"*50 + "\n")
        
        confirm_prompt = input("Proceed to call Gemini AI with this data? (y/n): ")
        if confirm_prompt.lower() != 'y':
            print("AI call aborted.")
            return

    print("Extracting data and calling Gemini...")
    summary_text = ai_service.generate_weekly_summary(data_summary)
    
    print("\n" + "="*50)
    print("PROPOSED SUMMARY:")
    print("="*50)
    print(summary_text)
    print("="*50 + "\n")

    if args.dry_run:
        print("Dry run complete. No actions taken.")
        return

    confirm = input("Approve this summary and broadcast? (y/n): ")
    if confirm.lower() != 'y':
        print("Broadcast cancelled.")
        return

    print("Saving to Firestore...")
    db_service.save_weekly_recap(args.year, args.week, summary_text)
    
    if emails:
        print(f"Sending emails to {len(emails)} players...")
        html_body = build_recap_html(args.week, summary_text)
        success = send_weekly_recap_email(emails, f"Week {args.week} Recap - Wins Pool", html_body)
        if success:
            print("Emails sent successfully!")
        else:
            print("Failed to send some or all emails.")
    else:
        print("No valid player emails found to notify.")

    print("Done!")

if __name__ == "__main__":
    main()
